In [1]:
import polars as pl 
from dbconfig import engine
print('Environment ready!')

Environment ready!

In [15]:
df = pl.read_csv("inflation_rates.csv")

In [3]:
df.head()

shape: (5, 44)
┌───────────┬────────────┬────────────┬────────┬───┬────────────┬────────────┬──────────┬──────────┐
│ STRUCTURE ┆ STRUCTURE_ ┆ STRUCTURE_ ┆ ACTION ┆ … ┆ DURABILITY ┆ Durability ┆ DECIMALS ┆ Decimals │
│ ---       ┆ ID         ┆ NAME       ┆ ---    ┆   ┆ ---        ┆ ---        ┆ ---      ┆ ---      │
│ str       ┆ ---        ┆ ---        ┆ str    ┆   ┆ str        ┆ str        ┆ i64      ┆ str      │
│           ┆ str        ┆ str        ┆        ┆   ┆            ┆            ┆          ┆          │
╞═══════════╪════════════╪════════════╪════════╪═══╪════════════╪════════════╪══════════╪══════════╡
│ DATAFLOW  ┆ OECD.SDD.T ┆ Consumer   ┆ I      ┆ … ┆ null       ┆ null       ┆ 2        ┆ Two      │
│           ┆ PS:DSD_PRI ┆ price      ┆        ┆   ┆            ┆            ┆          ┆          │
│           ┆ CES@DF_PRI ┆ indices    ┆        ┆   ┆            ┆            ┆          ┆          │
│           ┆ …          ┆ (CPIs, …   ┆        ┆   ┆            ┆            ┆          ┆          │
│ DATAFLOW  ┆ OECD.SDD.T ┆ Consumer   ┆ I      ┆ … ┆ null       ┆ null       ┆ 2        ┆ Two      │
│           ┆ PS:DSD_PRI ┆ price      ┆        ┆   ┆            ┆            ┆          ┆          │
│           ┆ CES@DF_PRI ┆ indices    ┆        ┆   ┆            ┆            ┆          ┆          │
│           ┆ …          ┆ (CPIs, …   ┆        ┆   ┆            ┆            ┆          ┆          │
│ DATAFLOW  ┆ OECD.SDD.T ┆ Consumer   ┆ I      ┆ … ┆ null       ┆ null       ┆ 2        ┆ Two      │
│           ┆ PS:DSD_PRI ┆ price      ┆        ┆   ┆            ┆            ┆          ┆          │
│           ┆ CES@DF_PRI ┆ indices    ┆        ┆   ┆            ┆            ┆          ┆          │
│           ┆ …          ┆ (CPIs, …   ┆        ┆   ┆            ┆            ┆          ┆          │
│ DATAFLOW  ┆ OECD.SDD.T ┆ Consumer   ┆ I      ┆ … ┆ null       ┆ null       ┆ 2        ┆ Two      │
│           ┆ PS:DSD_PRI ┆ price      ┆        ┆   ┆            ┆            ┆          ┆          │
│           ┆ CES@DF_PRI ┆ indices    ┆        ┆   ┆            ┆            ┆          ┆          │
│           ┆ …          ┆ (CPIs, …   ┆        ┆   ┆            ┆            ┆          ┆          │
│ DATAFLOW  ┆ OECD.SDD.T ┆ Consumer   ┆ I      ┆ … ┆ null       ┆ null       ┆ 2        ┆ Two      │
│           ┆ PS:DSD_PRI ┆ price      ┆        ┆   ┆            ┆            ┆          ┆          │
│           ┆ CES@DF_PRI ┆ indices    ┆        ┆   ┆            ┆            ┆          ┆          │
│           ┆ …          ┆ (CPIs, …   ┆        ┆   ┆            ┆            ┆          ┆          │
└───────────┴────────────┴────────────┴────────┴───┴────────────┴────────────┴──────────┴──────────┘

In [4]:
df.describe()

shape: (9, 45)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬──────────┐
│ statistic  ┆ STRUCTURE ┆ STRUCTURE ┆ STRUCTURE ┆ … ┆ DURABILIT ┆ Durabilit ┆ DECIMALS ┆ Decimals │
│ ---        ┆ ---       ┆ _ID       ┆ _NAME     ┆   ┆ Y         ┆ y         ┆ ---      ┆ ---      │
│ str        ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ str      │
│            ┆           ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆          ┆          │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪══════════╡
│ count      ┆ 31        ┆ 31        ┆ 31        ┆ … ┆ 0         ┆ 0         ┆ 68.0     ┆ 68       │
│ null_count ┆ 37        ┆ 37        ┆ 37        ┆ … ┆ 68        ┆ 68        ┆ 0.0      ┆ 0        │
│ mean       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 2.0      ┆ null     │
│ std        ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.0      ┆ null     │
│ min        ┆ DATAFLOW  ┆ OECD.SDD. ┆ Consumer  ┆ … ┆ null      ┆ null      ┆ 2.0      ┆ Two      │
│            ┆           ┆ TPS:DSD_P ┆ price     ┆   ┆           ┆           ┆          ┆          │
│            ┆           ┆ RICES@DF_ ┆ indices   ┆   ┆           ┆           ┆          ┆          │
│            ┆           ┆ PRI…      ┆ (CPIs, …  ┆   ┆           ┆           ┆          ┆          │
│ 25%        ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 2.0      ┆ null     │
│ 50%        ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 2.0      ┆ null     │
│ 75%        ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 2.0      ┆ null     │
│ max        ┆ DATAFLOW  ┆ OECD.SDD. ┆ Consumer  ┆ … ┆ null      ┆ null      ┆ 2.0      ┆ Two      │
│            ┆           ┆ TPS:DSD_P ┆ price     ┆   ┆           ┆           ┆          ┆          │
│            ┆           ┆ RICES@DF_ ┆ indices   ┆   ┆           ┆           ┆          ┆          │
│            ┆           ┆ PRI…      ┆ (CPIs, …  ┆   ┆           ┆           ┆          ┆          │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴──────────┘

In [7]:
df.shape

(68, 44)

In [17]:
df = df.select(
        pl.col('Observation').alias('year'),
        pl.col('OBS_STATUS').alias('inflation_rate')
        )

In [18]:
df.head()

shape: (5, 2)
┌──────┬────────────────┐
│ year ┆ inflation_rate │
│ ---  ┆ ---            │
│ i64  ┆ f64            │
╞══════╪════════════════╡
│ 1995 ┆ 10.22489       │
│ 1996 ┆ 8.977149       │
│ 1997 ┆ 7.164254       │
│ 1998 ┆ 13.23084       │
│ 1999 ┆ 4.669821       │
└──────┴────────────────┘

In [19]:
df = df.with_columns(
    pl.col("inflation_rate").round(2)
)

In [20]:
df.head()

shape: (5, 2)
┌──────┬────────────────┐
│ year ┆ inflation_rate │
│ ---  ┆ ---            │
│ i64  ┆ f64            │
╞══════╪════════════════╡
│ 1995 ┆ 10.22          │
│ 1996 ┆ 8.98           │
│ 1997 ┆ 7.16           │
│ 1998 ┆ 13.23          │
│ 1999 ┆ 4.67           │
└──────┴────────────────┘

In [21]:
df.describe()

shape: (9, 3)
┌────────────┬──────────┬────────────────┐
│ statistic  ┆ year     ┆ inflation_rate │
│ ---        ┆ ---      ┆ ---            │
│ str        ┆ f64      ┆ f64            │
╞════════════╪══════════╪════════════════╡
│ count      ┆ 31.0     ┆ 31.0           │
│ null_count ┆ 37.0     ┆ 37.0           │
│ mean       ┆ 2010.0   ┆ 6.494194       │
│ std        ┆ 9.092121 ┆ 2.840829       │
│ min        ┆ 1995.0   ┆ 2.49           │
│ 25%        ┆ 2003.0   ┆ 4.3            │
│ 50%        ┆ 2010.0   ┆ 5.8            │
│ 75%        ┆ 2018.0   ┆ 8.86           │
│ max        ┆ 2025.0   ┆ 13.23          │
└────────────┴──────────┴────────────────┘

In [22]:
df.schema

Schema([('year', Int64), ('inflation_rate', Float64)])

In [23]:
df

shape: (68, 2)
┌──────┬────────────────┐
│ year ┆ inflation_rate │
│ ---  ┆ ---            │
│ i64  ┆ f64            │
╞══════╪════════════════╡
│ 1995 ┆ 10.22          │
│ 1996 ┆ 8.98           │
│ 1997 ┆ 7.16           │
│ 1998 ┆ 13.23          │
│ 1999 ┆ 4.67           │
│ …    ┆ …              │
│ null ┆ null           │
│ null ┆ null           │
│ null ┆ null           │
│ null ┆ null           │
│ null ┆ null           │
└──────┴────────────────┘

In [24]:
df = df.drop_nulls()

In [25]:
df

shape: (31, 2)
┌──────┬────────────────┐
│ year ┆ inflation_rate │
│ ---  ┆ ---            │
│ i64  ┆ f64            │
╞══════╪════════════════╡
│ 1995 ┆ 10.22          │
│ 1996 ┆ 8.98           │
│ 1997 ┆ 7.16           │
│ 1998 ┆ 13.23          │
│ 1999 ┆ 4.67           │
│ …    ┆ …              │
│ 2021 ┆ 4.89           │
│ 2022 ┆ 5.9            │
│ 2023 ┆ 5.55           │
│ 2024 ┆ 3.8            │
│ 2025 ┆ 2.8            │
└──────┴────────────────┘

In [26]:
df.describe()

shape: (9, 3)
┌────────────┬──────────┬────────────────┐
│ statistic  ┆ year     ┆ inflation_rate │
│ ---        ┆ ---      ┆ ---            │
│ str        ┆ f64      ┆ f64            │
╞════════════╪══════════╪════════════════╡
│ count      ┆ 31.0     ┆ 31.0           │
│ null_count ┆ 0.0      ┆ 0.0            │
│ mean       ┆ 2010.0   ┆ 6.494194       │
│ std        ┆ 9.092121 ┆ 2.840829       │
│ min        ┆ 1995.0   ┆ 2.49           │
│ 25%        ┆ 2003.0   ┆ 4.3            │
│ 50%        ┆ 2010.0   ┆ 5.8            │
│ 75%        ┆ 2018.0   ┆ 8.86           │
│ max        ┆ 2025.0   ┆ 13.23          │
└────────────┴──────────┴────────────────┘

In [27]:
df = df.with_columns(
    pl.col("year").cast(pl.Int32)
)

In [28]:
df.describe()

shape: (9, 3)
┌────────────┬──────────┬────────────────┐
│ statistic  ┆ year     ┆ inflation_rate │
│ ---        ┆ ---      ┆ ---            │
│ str        ┆ f64      ┆ f64            │
╞════════════╪══════════╪════════════════╡
│ count      ┆ 31.0     ┆ 31.0           │
│ null_count ┆ 0.0      ┆ 0.0            │
│ mean       ┆ 2010.0   ┆ 6.494194       │
│ std        ┆ 9.092121 ┆ 2.840829       │
│ min        ┆ 1995.0   ┆ 2.49           │
│ 25%        ┆ 2003.0   ┆ 4.3            │
│ 50%        ┆ 2010.0   ┆ 5.8            │
│ 75%        ┆ 2018.0   ┆ 8.86           │
│ max        ┆ 2025.0   ┆ 13.23          │
└────────────┴──────────┴────────────────┘

In [29]:
df.schema

Schema([('year', Int32), ('inflation_rate', Float64)])

In [30]:
df.write_database(
    table_name="analysis.inflation",
    connection=engine,
    if_table_exists="replace",
)

-1

In [32]:
pl.read_database(
        query = """
        select table_name,
        column_name
        from information_schema.columns
        where table_schema = 'analysis'
        order by table_name, ordinal_position;
        """, connection = engine
        )

shape: (9, 2)
┌───────────────┬────────────────┐
│ table_name    ┆ column_name    │
│ ---           ┆ ---            │
│ str           ┆ str            │
╞═══════════════╪════════════════╡
│ inflation     ┆ year           │
│ inflation     ┆ inflation_rate │
│ nifty_monthly ┆ date           │
│ nifty_monthly ┆ price          │
│ nifty_monthly ┆ open           │
│ nifty_monthly ┆ high           │
│ nifty_monthly ┆ low            │
│ nifty_monthly ┆ volume         │
│ nifty_monthly ┆ change_pct     │
└───────────────┴────────────────┘